name: Build

on:
  push:
    branches:
      - main
    paths:
      - 'main.go'
      - 'filter.jq'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.24

      - name: Build geosite
        id: build
        env:
          GOAMD64: v3
          NO_SKIP: true
        run: |
          go run -v .

      ## TODO: This is dumb
      - name: Build custom logical rules
        env:
          SB_BIN_URL: https://github.com/SagerNet/sing-box/releases/download/v1.11.4/sing-box-1.11.4-linux-amd64.tar.gz
        run: |
          curl -sSLO $SB_BIN_URL
          tar xf sing-box-*-linux-amd64.tar.gz
          cp sing-box-*-linux-amd64/sing-box ./
          jq -cn --slurpfile include publish/geosite_cn.json --slurpfile exclude publish/geosite_geolocation-!cn.json -f filter.jq > publish/custom_logical_cn.json
          ./sing-box rule-set compile publish/custom_logical_cn.json
