name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.24

      - name: Build geosite
        id: build
        env:
          GOAMD64: v3
          NO_SKIP: true
        run: |
          go run -v .

      ## TODO: This is dumb
      - name: Build custom logical rules
        env:
          SB_BIN_URL: https://github.com/SagerNet/sing-box/releases/download/v1.11.3/sing-box-1.11.3-linux-amd64.tar.gz
        run: |
          curl -sSLO $SB_BIN_URL
          tar xf sing-box-*-linux-amd64.tar.gz
          cp sing-box-*-linux-amd64/sing-box ./
          ./sing-box rule-set decompile publish/geosite_cn.srs -o geosite_cn.json
          ./sing-box rule-set decompile publish/geosite_geolocation-!cn.srs -o geosite_non_cn.json
          jq -cn --slurpfile include geosite_cn.json --slurpfile exclude geosite_non_cn.json -f filter.jq > custom_logical_cn.json
          ./sing-box rule-set compile publish/custom_logical_cn.json -o publish/custom_logical_cn.srs
