name: Release

on:
  workflow_dispatch:
  schedule:
    - cron: "10 22 * * *" # 10min after loyalsoldier/v2ray-rules-dat

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.24

      - name: Build geosite
        id: build
        env:
          GOAMD64: v3
        run: |
          go run -v .

      ## TODO: This is dumb
      - name: Build custom logical rules
        if: steps.build.outputs.skip != 'true'
        env:
          SB_BIN_URL: https://github.com/SagerNet/sing-box/releases/download/v1.11.4/sing-box-1.11.4-linux-amd64.tar.gz
        run: |
          curl -sSLO $SB_BIN_URL
          tar xf sing-box-*-linux-amd64.tar.gz
          cp sing-box-*-linux-amd64/sing-box ./
          jq -cn --slurpfile include publish/geosite_cn.json --slurpfile exclude publish/geosite_geolocation-!cn.json -f filter.jq > publish/custom_logical_cn.json
          ./sing-box rule-set compile publish/custom_logical_cn.json

      - uses: dev-drprasad/delete-older-releases@v0.3.2
        if: steps.build.outputs.skip != 'true'
        with:
          keep_latest: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish release branch
        if: steps.build.outputs.skip != 'true'
        run: |
          cd publish || exit 1
          git init
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git branch -M release
          git add .
          git commit -m "${{ steps.build.outputs.tag }}"
          git push -f -u origin release

      - name: Release common rule sets
        if: steps.build.outputs.skip != 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.build.outputs.tag }}
          files: |
            publish/custom_logical_cn.srs
            publish/geosite_cn.srs
            publish/geosite_geolocation-!cn.srs
            publish/geosite_category-ads-all.srs

      - name: Purge jsdelivr cache
        if: steps.build.outputs.skip != 'true'
        run: |
          for file in cn geolocation-.cn category-ads-all; do
            curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@release/geosite_${file}.srs"
          done
          for file in cn; do
            curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@release/custom_logical_${file}.srs"
          done
